import {
	ChangeDetectionStrategy,
	Component,
	inject,
	signal,
} from '@angular/core'
import { ZardCheckboxComponent } from '../../ui/checkbox'
import { Z_MODAL_DATA } from '../../ui/dialog'

@Component({
	selector: 'app-delete-recurring-dialog',
	template: `
    <div class="flex flex-col gap-4 mt-2 mb-2">
      <p class="text-sm text-muted-foreground mb-4">Are you sure you want to delete the recurring entry "{{ data.description }}"? This action cannot be undone.</p>
      <label class="flex items-center gap-3 cursor-pointer">
        <z-checkbox class="border-input"
        (checkChange)="deleteTransactions.set($event)" />
        <span class="text-sm">Also delete all transactions generated by this recurring</span>
      </label>
    </div>
  `,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ZardCheckboxComponent],
})
export class DeleteRecurringDialog {
	readonly data = inject<{ description: string }>(Z_MODAL_DATA)
	readonly deleteTransactions = signal(false)
}
