import {
	Bandage,
	Briefcase,
	Bus,
	Car,
	ChartNoAxesCombined,
	CircleDollarSign,
	Coffee,
	Dumbbell,
	Film,
	Fuel,
	Gamepad2,
	Gift,
	GraduationCap,
	HeartPulse,
	House,
	Joystick,
	Lightbulb,
	type LucideIconData,
	Music,
	PawPrint,
	Plane,
	Repeat2,
	RotateCcw,
	Shirt,
	ShoppingBag,
	ShoppingBasket,
	ShoppingCart,
	Tag,
	TrendingUp,
	Utensils,
	Wifi,
	Wine,
	Wrench,
} from 'lucide-angular'

export const CATEGORY_ICON_MAP: Record<string, LucideIconData> = {
	utensils: Utensils,
	coffee: Coffee,
	wine: Wine,
	'shopping-basket': ShoppingBasket,
	car: Car,
	bus: Bus,
	fuel: Fuel,
	plane: Plane,
	house: House,
	lightbulb: Lightbulb,
	wifi: Wifi,
	wrench: Wrench,
	'gamepad-2': Gamepad2,
	music: Music,
	film: Film,
	dumbbell: Dumbbell,
	briefcase: Briefcase,
	'trending-up': TrendingUp,
	'circle-dollar-sign': CircleDollarSign,
	'repeat-2': Repeat2,
	gift: Gift,
	shirt: Shirt,
	'graduation-cap': GraduationCap,
	'heart-pulse': HeartPulse,
	'paw-print': PawPrint,
	'shopping-cart': ShoppingCart,
	tag: Tag,
	'chart-no-axes-combined': ChartNoAxesCombined,
	'shopping-bag': ShoppingBag,
	'rotate-ccw': RotateCcw,
	joystick: Joystick,
	bandage: Bandage,
}

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICON_MAP)
